---
# main task for role execution
- name: configure inventory hosts
  hosts: localhost
  gather_facts: no
  
  vars:
    linux_hosts: "{{ survey_hosts.split('\n') }}"  
  
  tasks:
    
  - name: make host group from survey hosts list
    add_host:
      hostname: "{{ item }}"
      groupname: host_group      
    loop: "{{ linux_hosts }}"

- name: configure automount shares on hosts
  hosts: host_group:!localhost
  gather_facts: true
  become: true
  
  tasks:
  
  - name: mount shares
    include_role:
      name: mount_shares
