---
# default variables for mount_shares role

packages:
  - family: RedHat
    name:
      - nfs-utils
      - cifs-utils
  - family: Debian
    name:
      - nfs-common
      - cifs-utils

cifs_user: <user>
cifs_pass: <password>

mounts:

  - src: "x.x.x.x:/path/to/source"
    path: "/mnt/directory/path"
    type: nfs #can be nfs or cifs
    opts: "defaults"
    
  - src: "//x.x.x.x/share/path"
    path: "/mnt/share"
    type: cifs 
    opts: "uid=0,credentials=/etc/cifspassword,iocharset=utf8,vers=3.0,noperm"
    # these opts are required for cifs mount

