---
# main tasks for mount_shares role

- name: install required packages
  package:
    name: "{{ item.packages }}"
    state: present
  when: item.family == ansible_os_family
  loop:
    - { family: 'RedHat', packages: 'nfs-utils, cifs-utils' }
    - { family: 'Debian', packages: 'nfs-common, cifs-utils' }

- name: create mount paths
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  loop:
   - /mnt/repository
   - /mnt/data-ssd

- name: make cifs credentials file
  lineinfile:
    path: /etc/cifspassword
    create: true
    owner: root
    group: root
    mode: 0600
    line: "{{ item }}"
  loop:
    - "{{ cifs_user }}"
    - "{{ cifs_pass }}"

- name: configure Ubuntu for cifs mounts
  block:
  
  - name: check icharset utf8 exists
    stat:
      path: /lib/modules/{{ ansible_kernel }}/kernel/fs/nls/nls_utf8.ko
    register: stat_result

  - name: install kernel extra modules (ensures nsl_utf8.ko is present)
    package:
      name: linx-modules-extra-{{ansible_kernel}}
      state: present
    when: not stat_result.stat.exists
  
  when: ansible_os_family == Debian

- name: mount shares
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts }}"
    state: mounted
    fstype: "{{ item.type }}"
  loop:
   - { src: '10.0.0.5:/volume1/Repository', path: '/mnt/repository', opts: 'defaults', type: 'nfs' }
   - { src: '//10.0.0.9/data-ssd', path: '/mnt/data-ssd', opts: 'uid=0,credentials=/etc/cifspassword,iocharset=utf8,vers=3.0,noperm', type: 'cifs' }
