---
# main tasks for mount_shares role

- name: install required packages
  package:
    name: "{{ item.name | join(',') }}"
    state: present
  when: item.family == ansible_os_family
  loop: "{{ packages }}"
  
- name: create mount directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  loop: "{{ mounts }}"

- name: configure cifs credentials
  lineinfile:
    path: /etc/cifspassword
    create: true
    owner: root
    group: root
    mode: 0600
    line: "{{ item }}"
  loop:
    - "username={{ cifs_user }}"
    - "password={{ cifs_pass }}"
  no_log: true

- name: configure Ubuntu for cifs mounts
  block:
  
  - name: check icharset utf8 exists
    stat:
      path: "/lib/modules/{{ ansible_kernel }}/kernel/fs/nls/nls_utf8.ko"
    register: stat_result

  - name: install kernel extra modules (ensures nsl_utf8.ko is present)
    package:
      name: "linux-modules-extra-{{ ansible_kernel }}"
      state: present
    when: not stat_result.stat.exists
  
  when: ansible_os_family == "Debian"

- name: mount shares
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts }}"
    state: mounted
    fstype: "{{ item.type }}"
  loop: "{{ mounts }}"
